global:
  smtp_smarthost: 'smtp.gmail.com'
  smtp_from: 'alertmanager@example.com'
  smtp_require_tls: False
 
route:
  group_by: ['alertname', 'cluster']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: 'example'
 
receivers:
- name: 'example'
  email_configs:
  - to: 'dp7gotcha@gmail.com'