version: "3"  
services:  
 prometheus:
     image: prom/prometheus:latest
     networks:
       frontend:
         ipv4_address: 172.20.0.5
     ports:
       - 9090:9090
     volumes:
       - "./prometheus.yml:/etc/prometheus/prometheus.yml"
       - "./alerts.yml:/etc/prometheus/alerts.yml"
 grafana:
     image: grafana/grafana-enterprise
     networks:
       frontend:
         ipv4_address: 172.20.0.6
     ports:
       - 3000:3000
 app:
     container_name: app
     networks:
       frontend:
         ipv4_address: 172.20.0.7
     build: ./flask_api/.
     ports:
     - "5000:5000"
     volumes:
     - "./flask_api/app.py:/app.py"
networks:
  frontend:
    ipam:
      config:
        - subnet: 172.20.0.0/24
